{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hr-backend.fullname" . }}-secret
  labels:
    {{- include "hr-backend.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}