version: '3.8'

services:
  web:
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    external_links:
      - postgres17:postgres
      - elasticsearch:elasticsearch

networks:
  default:
    name: hr-system
    external: true
