# Generated by Django 5.2.3 on 2025-07-01 16:27

import django.core.validators
import django.db.models.deletion
import job_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Candidate's full name", max_length=255)),
                ('email', models.EmailField(help_text='Unique email address for the candidate', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Unique phone number for the candidate', max_length=20, unique=True)),
                ('date_of_birth', models.DateField(help_text="Candidate's date of birth")),
                ('years_of_experience', models.PositiveIntegerField(help_text='Years of professional experience', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FINANCE', 'Finance')], help_text='Department the candidate is applying for', max_length=20)),
                ('resume', models.FileField(help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=job_application.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', help_text='Current application status', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Registration timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department'], name='job_applica_departm_b0e43c_idx'), models.Index(fields=['status'], name='job_applica_status_0ced13_idx'), models.Index(fields=['created_at'], name='job_applica_created_09beb2_idx'), models.Index(fields=['email'], name='job_applica_email_e28e64_idx'), models.Index(fields=['phone_number'], name='job_applica_phone_n_212eb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], help_text='Previous status before the change', max_length=30, null=True)),
                ('new_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], help_text='New status after the change', max_length=30)),
                ('comments', models.TextField(blank=True, help_text='Comments or feedback for the status change')),
                ('changed_by', models.CharField(default='admin', help_text='Who made the status change', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the status was changed')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='job_application.candidate')),
            ],
            options={
                'verbose_name_plural': 'Status histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='status_update', help_text='Type of notification sent', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was sent')),
                ('success', models.BooleanField(default=True, help_text='Whether the notification was sent successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='job_application.candidate')),
                ('status_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='job_application.statushistory')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['candidate', '-changed_at'], name='job_applica_candida_b3bac5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['candidate'], name='job_applica_candida_77f112_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='job_applica_sent_at_862877_idx'),
        ),
    ]
