# Generated by Django 5.2.3 on 2025-07-05 01:18

import django.core.validators
import job_application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=job_application.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
