apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hr-frontend.fullname" . }}-config
  labels:
    {{- include "hr-frontend.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.nextjs.port | quote }}
  NEXT_PUBLIC_API_URL: {{ index .Values.env 1 "value" | quote }}